---
title: "About"
date: "2020-12-27"
slug: "about"
output:
 blogdown::html_page:
  highlight: tango
comments: false
showMeta: false
showActions: false
---
My name is Marc Sauter and I am a junior data scientist.

# How I found my way into data science

The first introductory statistics course I had at university was in year 2015 where I was using an installation of the statistical software R version 3.2.2. In the following semester I found myself joining a master's course on data science that would ultimately change my thinking. This is where I have picked up strategies to sort my files, have formed the habit of doing frequent backups, and have learned to apply statistical learning techniques. This was also when I have decided to switch from proprietary Windows to free software GNU Linux as my main operating system.

# Three reasons for writing this blog

First of all, during the past ten years I have absorbed a lot of information in my studies with only few chances to write about it. I have taken more than hundred exams and begin to realize that I want to start sharing knowledge before I sign my next work contract.

Furthermore, I am writing this blog because I want to keep track of my progression in data science. There are many obstacles to come.

Finally, I would like to improve my english communication skills to a native level.